import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/style/globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin","vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Laundry & Shoe Care Operations Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
